[package]
name = "shroud-debug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
shroud = { path = "../../", features = ["directx9", "directx11", "directx12"] }
windows = { version = "0.51.1", features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_Security", "Win32_System_Threading", "Win32_System_Console"] }
