on: [push, pull_request]

name: Continuous integration

jobs:

  check:
    name: Check
    runs-on: windows-latest
    strategy: 
      matrix:
        feature: [ directx9, directx10, directx11, directx12 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features ${{ matrix.feature }}

  test:
    name: Test Suite
    runs-on: windows-latest
    strategy: 
      matrix:
        feature: [ directx9, directx10, directx11, directx12 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ matrix.feature }}

  fmt:
    name: Rustfmt
    runs-on: windows-latest
    strategy: 
      matrix:
        feature: [ directx9, directx10, directx11, directx12 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --features ${{ matrix.feature }}

  clippy:
    name: Clippy
    runs-on: windows-latest
    strategy: 
      matrix:
        feature: [ directx9, directx10, directx11, directx12 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --features ${{ matrix.feature }}